name: thriftly
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.9.0
  cloud_firestore: ^4.3.1
  firebase_analytics: ^10.1.0
  google_fonts: ^3.0.1
  flutter_bloc: ^7.1.0
  firebase_auth: ^4.2.5
  equatable: ^2.0.5
  fl_chart: ^0.60.0
  percent_indicator: ^4.2.2
  flutter_snake_navigationbar: ^0.6.1
  intl: ^0.17.0
  image_picker: ^0.8.0
  firebase_storage: ^11.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter


  # flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/images/app-logo.png
    - assets/images/arrow-right-green.png

  uses-material-design: true