// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwyo8V5x5NDB3Ub31A8Av0wKCz1IYpd6I',
    appId: '1:225683684874:web:3dc56befdcb7cc3d30e9f3',
    messagingSenderId: '225683684874',
    projectId: 'thriftly-bc3f0',
    authDomain: 'thriftly-bc3f0.firebaseapp.com',
    storageBucket: 'thriftly-bc3f0.appspot.com',
    measurementId: 'G-40QN4D15V8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqG8YRKRVuijtPCN7qxaX9PO5E-PoBVHY',
    appId: '1:225683684874:android:33e2060e9a0f4d6030e9f3',
    messagingSenderId: '225683684874',
    projectId: 'thriftly-bc3f0',
    storageBucket: 'thriftly-bc3f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQnEo3KUJuvu_HQRlZF_oC4FJ2vVpR8xQ',
    appId: '1:225683684874:ios:f15ab7c1d8a356f930e9f3',
    messagingSenderId: '225683684874',
    projectId: 'thriftly-bc3f0',
    storageBucket: 'thriftly-bc3f0.appspot.com',
    iosClientId: '225683684874-q0l5lftnndsehej6o18qqfcivdkii8bk.apps.googleusercontent.com',
    iosBundleId: 'com.example.thriftly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQnEo3KUJuvu_HQRlZF_oC4FJ2vVpR8xQ',
    appId: '1:225683684874:ios:f15ab7c1d8a356f930e9f3',
    messagingSenderId: '225683684874',
    projectId: 'thriftly-bc3f0',
    storageBucket: 'thriftly-bc3f0.appspot.com',
    iosClientId: '225683684874-q0l5lftnndsehej6o18qqfcivdkii8bk.apps.googleusercontent.com',
    iosBundleId: 'com.example.thriftly',
  );
}
